# Generated by Django 2.2.5 on 2019-10-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='men',
            name='image',
            field=models.ImageField(default='', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='women',
            name='image',
            field=models.ImageField(default='', upload_to='products'),
        ),
    ]
